### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: on predict.py

### ISSUE THREAD

**Issue by KanimozhiU** [jiegzhan/multi-class-text-classification-cnn#11]
Traceback (most recent call last):
  File "predict.py", line 73, in <module>
    predict_unseen_data()
  File "predict.py", line 19, in predict_unseen_data
    checkpoint_file = tf.train.latest_checkpoint(checkpoint_dir + 'checkpoints')
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1602, in latest_checkpoint
    if file_io.get_matching_files(v2_path) or file_io.get_matching_files(
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 332, in get_matching_files
    for single_filename in filename
  File "/home/kanimozhiu/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/ubuntu/multi-class-text-classification-cnn/trained_model_1479757124/checkpoints

How to resolve this error?

**Comment by jiegzhan** [comment]
https://github.com/jiegzhan/multi-class-text-classification-cnn/issues/13

After training, I was able to see the saved model files and run predict.py
