### ISSUE TITLE
Error "not enough values to unpack" on predict

### ISSUE THREAD

**Issue by BitcoinKing** [jiegzhan/multi-class-text-classification-cnn#2]
When do predict i have got error after 7200 step:

```
CRITICAL:root:Saved model d:\Django\multi-class-text-classification-cnn\trained_model_1485372325\checkpoints\model-7200 at step 7200
CRITICAL:root:Best accuracy 0.8768386935926203 at step 7200
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    train_cnn()
  File "train.py", line 104, in train_cnn
    x_train_batch, y_train_batch = zip(*train_batch)
ValueError: not enough values to unpack (expected 2, got 0)
```

Accuracy is good and enough, but why error comes and what if it arise on low accurasy
(Anaconda python 3.5, dataset 47000 rows with Cyrillic chars)

**Comment by jiegzhan** [comment]
What's your batch_size?
Try changing the batch_size to 37. Or 67.
